services:
  - type: web
    name: fiddo-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    rootDir: "."  # <--- Asegura que use la raíz del proyecto
    branch: main
    autoDeploy: true
